name: tracmip
channels:
  - conda-forge
dependencies:
  - dask-kubernetes
  - gcsfs
  - intake-xarray
  - jupyter-server-proxy
  - jupyterlab
  - matplotlib
  - nc-time-axis
  - pip
  - xarray
  - zarr
  - pip:
    - dask-labextension
    - kubernetes
    - qgrid
