name: tracmip
channels:
  - conda-forge
dependencies:
  - dask-kubernetes
  - gcsfs
  - intake-xarray
  - jupyter-server-proxy
  - jupyterlab=1.0.9
  - matplotlib
  - nc-time-axis
  - pip
  - xarray
  - zarr
  - pip:
    - dask-labextension=1.0.0
    - kubernetes
