name: tracmip
channels:
  - conda-forge
dependencies:
  - xarray
  - dask-kubernetes
  - gcsfs
  - intake-xarray
  - zarr
  - nc-time-axis
  - matplotlib
  - jupyter-server-proxy
  - pip:
    - kubernetes
